- name: Deploy PD Allure Report
  hosts: localhost
  gather_facts: True
  vars_files:
    - ./vars/base.yml
  ## Tasks
  tasks:
  - name: add host
    add_host:
      name: "{{ deploymentPrefix }}"
      ansible_ssh_host: "{{ deploymentPrefix }}-pip-01.{{ azurelocation }}.cloudapp.azure.com"
      ansible_ssh_user: "{{ deploymentPrefix }}"
      ansible_ssh_port: 22
      ansible_ssh_private_key_file: "/etc/ansible/pems/{{ deploymentPrefix }}.pem"

  - import_tasks: includes/pd-report-azuredeploy.yml
    when: deployAzure | bool

- import_playbook: includes/pd-report-nginxdeploy.yml
  when: deployNginx | bool