- hosts: "pd-report"
  become: true
  become_method: sudo
  gather_facts: False
  pre_tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      delay: 30 # not required. Number of seconds to wait before starting to poll.
      sleep: 5 # not required. Number of seconds to sleep between checks.
      connect_timeout: 10 # not required. Maximum number of seconds to wait for a connection to happen before closing and retrying.
      timeout: 120 # not required. Maximum number of seconds to wait for.:
  - name: Gathering facts
    setup:
  tasks:
  - name: install nginx
    apt:
      name: nginx